name: page-tracker
services:
  web-service:
    build: .
    ports:
      - "80:8000"
    environment:
      - REDIS_URL=redis://redis-service:6379
    depends_on:
      - redis-service
    command: "gunicorn page_tracker.app:app --bind 0.0.0.0:8000"
  redis-service:
    image: redis:7.0.10-bullseye
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
  test-service:
    profiles:
      - testing
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REDIS_URL: "redis://redis-service:6379"
      FLASK_URL: "http://web-service:8000"
    depends_on:
      - redis-service
      - web-service
    command: >
      sh -c 'python -m pytest test/e2e/ -vv
      --redis-url $$REDIS_URL
      --flask-url $$FLASK_URL'
volumes:
  redis-volume:

