name: page-tracker
services:
  web-service:
    build: .
    ports:
      - "80:8000"
    environment:
      - REDIS_URL=redis://redis-service:6379
    depends_on:
      - redis-service
    command: "gunicorn page_tracker.app:app --bind 0.0.0.0:8000"
  redis-service:
    image: redis:7.0.10-bullseye
    volumes:
      - redis-volume:/data
volumes:
  redis-volume:

